services:
  db:
    image: postgres:15
    build: 
      context: .
      dockerfile: ./Dockerfiles/db.Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - "./secrets/db.env"
    ports:
      - "5432:5432"
    container_name: mtg-stats-database
    extra_hosts:
      - "localhost:127.0.0.1"
  pgadmin:
    image: dpage/pgadmin4:9.2.0
    ports:
      - "8888:80"
    env_file:
      - "./secrets/pgadmin.env"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    container_name: mtg-stats-pgadmin
  app:
    image: docker.io/library/stats:test
    build: 
      context: .
      dockerfile: ./Dockerfiles/app.Dockerfile
    healthcheck:
      test: curl -f http://localhost:5000/docker-status || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    env_file:
      - "./secrets/db.env"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    container_name: mtg-stats-app