services:
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - "./secrets/db.env"
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:9.2.0
    ports:
      - "8888:80"
    env_file:
      - "./secrets/pgadmin.env"
    depends_on:
      db:
        condition: service_healthy
    container_name: pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  api:
    build: 
      context: .
      dockerfile: ./Dockerfiles/api.Dockerfile
    env_file:
      - "./secrets/db.env"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    container_name: app
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfiles/frontend.Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend

volumes:
  pgadmin-data: 
    driver: local
  postgres-data: 
    driver: local